# Generated by Django 5.2.4 on 2025-08-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='The unique registration number of the letter.', unique=True)),
                ('subject', models.CharField(help_text='The subject of the letter.', max_length=255)),
                ('addressee', models.CharField(help_text="The name of the letter's addressee (e.g., NAPP).", max_length=255)),
                ('registered_by_username', models.CharField(help_text='Username of the person who registered the letter.', max_length=150)),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='The exact date and time the letter was registered.')),
                ('is_cancelled', models.BooleanField(default=False, help_text='True if the letter has been cancelled.')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
